name: Build
on:
  push:
    branches: [ "master" ]

jobs:
# Build job. Builds app for Android with npm
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.0.0]
    steps:
    - uses: actions/checkout@v4
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: |
          echo "Free space:"
          df -h
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: git clone https://github.com/brave/brave-core.git ./src/brave
    - run: cd ./src/brave
    - run: npm install --force
  #  - run: npm i semver log-update node-fetch@2.6.1 gclient
  #  - run: npm run sync brave_core_ref
    - run: npm run init
    - run: npm config set target_os android
    - run: npm config set target_arch arm
    - run: npm run build Release
   
         
#    - name: Build with npm
 #     run: |
  #        cd ${{ github.workspace }}
   #       buildozer android debug
   # - name: Upload artifacts
   #   uses: actions/upload-artifact@v2
    #  with:
     #     name: package
      #    path: bin/*.apk
        #  path: ${{ steps.buildozer.outputs.filename }}
